USE CINeeds;

INSERT INTO CIN_Post VALUE (1, 1, "food", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post VALUE (2, 2, "housing", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post VALUE (3, 3, "financial", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post VALUE (4, 1, "health", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post VALUE (5, 2, "academic", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post VALUE (6, 3, "other", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post VALUE (7, 1, "food", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post VALUE (8, 2, "housing", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post VALUE (9, 3, "financial", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post VALUE (10, 1, "health", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
