USE cineedsc_db;

-- INSERT INTO CIN_Post (userID, postType, category, postTitle, postData, postDate, offerExpDate) VALUE (1, 1, "Request", "food", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post (userID, postType, category, postTitle, postData, postDate, offerExpDate) VALUE (2, 2, "Request", "housing", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post (userID, postType, category, postTitle, postData, postDate, offerExpDate) VALUE (3, 3, "Request", "financial", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post (userID, postType, category, postTitle, postData, postDate, offerExpDate) VALUE (4, 1, "Request", "health", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post (userID, postType, category, postTitle, postData, postDate, offerExpDate) VALUE (5, 2, "Request", "academic", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post (userID, postType, category, postTitle, postData, postDate, offerExpDate) VALUE (6, 3, "Request", "other", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post (userID, postType, category, postTitle, postData, postDate, offerExpDate) VALUE (7, 1, "Request", "food", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post (userID, postType, category, postTitle, postData, postDate, offerExpDate) VALUE (8, 2, "Request", "housing", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post (userID, postType, category, postTitle, postData, postDate, offerExpDate) VALUE (9, 3, "Request", "financial", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
INSERT INTO CIN_Post (userID, postType, category, postTitle, postData, postDate, offerExpDate) VALUE (10, 1, "Request", "health", "Testing", "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.", CURRENT_DATE(), null);
