USE cineedsc_db;

DROP PROCEDURE IF EXISTS ban_user;
DELIMITER //
CREATE PROCEDURE ban_user (IN inUserID INT) BEGIN UPDATE CIN_User SET banned = TRUE WHERE userID = inUserID; END//
DELIMITER ;

DROP PROCEDURE IF EXISTS flag_post;
DELIMITER //
CREATE PROCEDURE flag_post (IN inPostID INT) BEGIN UPDATE CIN_Post SET flagCount = flagCount + 1 WHERE postID = inPostID; END//
DELIMITER ;

SELECT * FROM CIN_User;
CALL ban_user(1);
SELECT * FROM CIN_User;